---
title: "About"
output: html_document
---

## About

Interactive dashboard to visualize reliability-based calibration results. Because we have more 
results than it could be put on a few plots.

**The data comes with the dashboard corresponds to the calibrated EN1992-1-1 shear 
resistance model and RC2 reliability class (referred to as case R1 in the
accompanying paper).**

**Best viewed on larger screens (not on mobile phones).**

Related links: 
* <a href="https://github.com/TNO/shear_calibration_shiny" target="_blank">source code of this dashboard</a>.
* <a href="https://github.com/TNO/shear_calibration" target="_blank">calibration code (to generate the results to be visualized)</a>.

Created by:
<div style="margin-left: 1em;">  
  Árpád Rózsás <br>   
  Arthur Slobbe
</div>
<br>

<p> Contact: 
<script language="JavaScript">
var username = "rozsasarpi";
var hostname = "gmail.com";
var linktext = username + "@" + hostname ;
document.write("<a href='" + "mail" + "to:" + username + "@" + hostname + "'>" + linktext + "</a>");
</script>; 
<script language="JavaScript">
var username = "arthur.slobbe";
var hostname = "tno.nl";
var linktext = username + "@" + hostname ;
document.write("<a href='" + "mail" + "to:" + username + "@" + hostname + "'>" + linktext + "</a>");
</script>
</p>


Licence: <a href="https://en.wikipedia.org/wiki/MIT_License" target="_blank">MIT</a>

***

The main packages used for this app: 
<a href="http://shiny.rstudio.com/" target="_blank">shiny</a>,
<a href="https://ggplot2.tidyverse.org/" target="_blank">ggplot2</a>.
