name: Deploy shiny app on shinyapps.io
on:
  push:

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install libcurl4
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install rsconnect
        run: |
          install.packages('rsconnect')
        shell: Rscript {0}
      - name: Deploy on shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='rozsasarpi', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'visualize_calibration_results')"
