# Partially based on: https://github.com/r-lib/actions/blob/245dbd85428574c5ffbcd0e2417f6966e2f4c789/examples/shiny-deploy.yaml

name: CI
on:
  push:

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/fix_deployment' && github.repository == 'TNO/shear_calibration_shiny'
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-renv@v2
        with:
          # If you need to invalidate the existing cache pass any other number and a new cache will be used.
          cache-version: 2
      # Needed for `rsconnect` to work
      - name: Install libcurl4
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install rsconnect
        run: |
          install.packages('rsconnect')
        shell: Rscript {0}
      - name: Authenticate and deploy on shinyapps.io
        run: |
          rsconnect::setAccountInfo(name='rozsasarpi', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
          rsconnect::deployApp(appDir='app/', appName = 'visualize_calibration_results' appFileManifest = 'files_to_deploy.txt')
        shell: Rscript {0}
